# Generated by Django 5.0.13 on 2026-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=40)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'conta bancaria',
                'verbose_name_plural': 'contas bancarias',
                'ordering': ['banco', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mes', models.DateField(help_text='Use sempre o primeiro dia do mes.')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='Financeiro.categoria')),
            ],
            options={
                'ordering': ['-mes', 'categoria__nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagarReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago/Recebido')], default='aberto', max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_receber', to='Financeiro.categoria')),
            ],
            options={
                'verbose_name': 'conta a pagar/receber',
                'verbose_name_plural': 'contas a pagar/receber',
                'ordering': ['vencimento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('ofx', 'OFX'), ('excel', 'Excel')], max_length=10)),
                ('arquivo', models.FileField(upload_to='importacoes/%Y/%m/')),
                ('total_lancamentos', models.PositiveIntegerField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to='Financeiro.contabancaria')),
            ],
            options={
                'verbose_name': 'importacao',
                'verbose_name_plural': 'importacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('debito', 'Debito'), ('credito', 'Credito')], max_length=10)),
                ('identificador_externo', models.CharField(blank=True, max_length=120)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='Financeiro.contabancaria')),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='Financeiro.importacao')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RateioLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios', to='Financeiro.categoria')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='Financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'rateio de lancamento',
                'verbose_name_plural': 'rateios de lancamentos',
                'ordering': ['lancamento', 'categoria'],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('categoria', 'mes'), name='budget_unico_por_categoria_mes'),
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador_externo', ''), _negated=True), fields=('conta', 'identificador_externo'), name='lancamento_unico_por_conta_e_identificador'),
        ),
    ]
