# Generated by Django 5.0.13 on 2026-05-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_evento_contapagarreceber_evento_lancamento_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagarreceber',
            name='lancamento_conciliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_conciliadas', to='Financeiro.lancamento'),
        ),
    ]
