# Generated by Django 5.0.13 on 2026-05-19 12:57

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0003_contapagarreceber_lancamento_conciliado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorrenciaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=180)),
                ('frequencia', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'recorrencia de conta',
                'verbose_name_plural': 'recorrencias de contas',
                'ordering': ['-data_inicio', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='contapagarreceber',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='Financeiro.recorrenciaconta'),
        ),
    ]
