# Generated by Django 5.0.13 on 2026-05-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0004_recorrenciaconta_alter_importacao_origem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo', 'pai__nome', 'nome']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='Financeiro.categoria', verbose_name='conta pai'),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='origem',
            field=models.CharField(choices=[('ofx', 'OFX'), ('excel', 'Cartao de Credito')], max_length=10),
        ),
    ]
