# Generated by Django 5.0.13 on 2026-05-20 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0005_alter_categoria_options_categoria_pai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='data_saldo_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
